version: '3'

services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - $WEB_PORT:80
    volumes:
      - ./src:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    image: m5d215/php-fpm-postgres:7-stretch
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html:ro

  db:
    image: postgres:12-alpine
    restart: unless-stopped
    ports:
      - $POSTGRES_PORT:5432
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
