version: '3'

services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - $WEB_PORT:80
    volumes:
      - ./images:/var/www/html/images:ro
      - ./src/api:/var/www/html/api:ro
      - ./src/components:/var/www/html/components:ro
      - ./src/css:/var/www/html/css:ro
      - ./src/db:/var/www/html/db:ro
      - ./src/js:/var/www/html/js:ro
      - ./src/login:/var/www/html/login:ro
      - ./src/logout:/var/www/html/logout:ro
      - ./src/pages:/var/www/html/pages:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    image: m5d215/php-fpm-postgres:7-stretch
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html:ro
      - ./images:/images
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    ports:
      - $POSTGRES_PORT:5432
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
